tools:
    php_analyzer: true

filter:
    excluded_paths:
        - 'vendor/*'

# Say to Scrutinizer to use pre-installed PHP instead of compiling one
build:
    environment:
        php:
            version: '8.2' 
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run